# Generated by Django 5.0.6 on 2024-06-23 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_user'),
        ('expense', '0007_alter_expense_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ExpenseCategory',
        ),
    ]
